# Generated by Django 4.2.2 on 2023-07-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_adoptantes_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptantes',
            name='edad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='adoptantes',
            name='mensaje',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptantes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
